version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    container_name: php-apache-container
    networks:
      - php-network

networks:
  php-network:
    driver: bridge

